### ISSUE TITLE
Looping pressed key on restore session's login screen

### ISSUE THREAD

**Issue by lgmventura** [mate-desktop/mate-desktop.org#102]
Ubuntu 18.04 (not Ubuntu MATE) with MATE desktop installed manually by APT: Login screen for restoring session often looping the first pressed key (when typing password; no release key signal being processed). So, the keyboard freezes completely (not even pressing the same key again solves) and there is no other possibility like CTRL+ALT+F1. Since I'm using a laptop, I can't try reconnecting the keyboard physically. The only remaining solution is holding the laptop on/off button until it forcibly turns off.

**Comment by yetist** [comment]
Thank you for submitting the bug, but this repo is used to maintain the https://mate-desktop.org website, and you should submit a bug report to the correct DM, such as lightm.
