### ISSUE TITLE
Preview each PR?

### ISSUE THREAD

**Issue by yetist** [mate-desktop/mate-desktop.org#109]
I hope to be able to preview each PR.

When anyone opens a pull request, it can build html files on travis and have a website preview, perhaps to use the github pages website https://mate-desktop.github.io/mate-desktop.org?

The official website will be automatically updated whenever there is any commit, not a PR.

There is a issue with CI/CI now, see #80 and https://github.com/mate-desktop/mate-desktop.org/pull/107#issuecomment-464950584

**Comment by yetist** [comment]
@mate-desktop/website-maintainers

Any ideas?

**Comment by yetist** [comment]
It works, demo is here https://github.com/yetist/mate-desktop.org/pull/1

**Comment by sc0w** [comment]
It is a great idea! and it seems to work!

**Comment by yetist** [comment]
Add watermark for preview: https://yetist.github.io/mate-desktop.org/

**Comment by yetist** [comment]
After c96ca42b97d1fe55694fb2d3eb830274b39a7d87, the requirements have been implemented
