### ISSUE TITLE
Outdated instructions on Download page.

### ISSUE THREAD

**Issue by ghost** [mate-desktop/mate-desktop.org#160]
https://wiki.mate-desktop.org/download This page is heavily outdated. Please, update it with newer MATE versions and newer distributions.

**Comment by lukefromdc** [comment]
You are not kidding: it still lists MATE 1.8 as current. The package names for Debian are still valid, but the versions are 5-7 cycles back.

**Comment by raveit65** [comment]
Closing. user doesn't have a github account any more.
Wiki is moved to https://github.com/mate-desktop/mate-wiki an can be updated now.
