### ISSUE TITLE
ERROR https://wiki.mate-desktop.org/download

### ISSUE THREAD

**Issue by huezo** [mate-desktop/mate-desktop.org#161]
ERROR https://wiki.mate-desktop.org/download

![Captura de pantalla de 2019-09-17 14-43-15](https://user-images.githubusercontent.com/15940634/65200372-ca1be300-da43-11e9-8849-1757831cc438.png)

**Comment by raveit65** [comment]
Mate-wiki links are fixed now.
https://github.com/mate-desktop/mate-desktop.org/commit/f687fd2ebd741fe7e3b2c37d6ffa2667f08ded70
