### ISSUE TITLE
Broken links on the https://mate-desktop.org/development/ page

### ISSUE THREAD

**Issue by matei-dragu** [mate-desktop/mate-desktop.org#162]
Hey guys,

Some of the links on the https://mate-desktop.org/development/ page are broken - for example:
- MATE Development - https://wiki.mate-desktop.org/dev-doc
- MATE Roadmap - https://wiki.mate-desktop.org/roadmap

It would be nice to have them restored so that interested people can get the desired information.

Cheers!

**Comment by raveit65** [comment]
Wiki has changed, for the moment search here.
https://mate-desktop.github.io/mate-wiki/#!index.md

**Comment by matei-dragu** [comment]
Thanks for the link @raveit65 !
Are there any plans to fix the links on the website as well?

**Comment by raveit65** [comment]
yes, iTs on TODO list.

**Comment by matei-dragu** [comment]
Good to hear, thanks @raveit65 !

**Comment by raveit65** [comment]
Links are updated now.
https://github.com/mate-desktop/mate-desktop.org/commit/f687fd2ebd741fe7e3b2c37d6ffa2667f08ded70
