### ISSUE TITLE
mate-desktop.org is expired and parked

### ISSUE THREAD

**Issue by jonathonf** [mate-desktop/mate-desktop.org#194]
The project's main domain is expired and now parked, presumably sniped by a third-party.

I can recommend [fosshost.org](https://fosshost.org) for managed domain hosting should it be required.

I can register some alternatives if required - other TLDs are available. I love MATE and am perfectly happy to fund that for a year (or ongoing as needed).

```
$ whois mate-desktop.org
Domain Name: MATE-DESKTOP.ORG
Registry Domain ID: D164017185-LROR
Registrar WHOIS Server: whois.godaddy.com
Registrar URL: http://www.whois.godaddy.com
Updated Date: 2020-12-07T13:58:39Z
Creation Date: 2011-12-02T14:12:37Z
Registry Expiry Date: 2021-12-02T14:12:37Z
Registrar Registration Expiration Date:
Registrar: GoDaddy.com, LLC
Registrar IANA ID: 146
Registrar Abuse Contact Email: abuse@godaddy.com
Registrar Abuse Contact Phone: +1.4806242505
Reseller:
Domain Status: clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited
Domain Status: clientRenewProhibited https://icann.org/epp#clientRenewProhibited
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Domain Status: clientUpdateProhibited https://icann.org/epp#clientUpdateProhibited
Domain Status: autoRenewPeriod https://icann.org/epp#autoRenewPeriod
Registrant Organization: Domains By Proxy, LLC
Registrant State/Province: Arizona
Registrant Country: US
Name Server: NS75.DOMAINCONTROL.COM
Name Server: NS76.DOMAINCONTROL.COM
DNSSEC: unsigned
```

![image](https://user-images.githubusercontent.com/559369/101562669-bc8fa780-39bf-11eb-9e83-76aacf1f5224.png)

**Comment by lukefromdc** [comment]
I myself can do nothing about this. As for finances, I have no online financial accounts and also do not have paid employment.

**Comment by raveit65** [comment]
all our dns is in hand of @flexiondotorg 
Martin, action is needed.

**Comment by flexiondotorg** [comment]
The automatic payment processing failed. I renewed the domain. Site is up and IntoDNS report is looking good.

  * https://intodns.com/mate-desktop.org
