### ISSUE TITLE
Wrong statement for Slackware inclusion

### ISSUE THREAD

**Issue by willysr** [mate-desktop/mate-desktop.org#26]
Hi,

I want to propose to change this text:
MATE is available via unofficial repositories for the following Linux distributions, but inclusion in their official repositories is planned:
    Slackware

into

MATE is available via unofficial repositories for the following Linux distributions:

    Slackware

The reason is that because we (for now) don't have plan to push MATE to core Slackware packages. The decision is not made by us, but by Patrick Volkerding, Slackware author and maintainer.

Thanks

**Comment by flexiondotorg** [comment]
#27 has been merged.
