### ISSUE TITLE
packages.mate-desktop.org is down

### ISSUE THREAD

**Issue by elacheche** [mate-desktop/mate-desktop.org#35]
Sorry if am reporting in the wrong place..

For 2 days now http://packages.mate-desktop.org is down.. So some users can't use it to update (if thee is any) or install packages..

**Comment by stefano-k** [comment]
I just updated DNS because that server is no more available

**Comment by elacheche** [comment]
The DNS propagation just finished.. It takes  24h to finish.. I highly recommend changing the TTL in all the DNS records to 600 or 300.. So next time we don't wait 24h for DNS propagation :) 

Anyway, the problem is not solved yet.. I think that you change the apache2 configuration because the it catch http://packages.mate-desktop.org as http://mate-desktop.org so it's a natural thing if we still can't update :)

> W: Failed to fetch http://packages.mate-desktop.org/repo/ubuntu/dists/precise/main/binary-amd64/Packages  404  Not Found
> W: Failed to fetch http://packages.mate-desktop.org/repo/ubuntu/dists/precise/main/binary-i386/Packages  404  Not Found
> E: Some index files failed to download. They have been ignored, or old ones used instead.
