### ISSUE TITLE
mate-desktop.org is not encrypted

### ISSUE THREAD

**Issue by physicsshark** [mate-desktop/mate-desktop.org#36]
Not a huge issue, I would think (because I don't think you're transmitting sensitive information), but it's 2015 and a lot of people would like to see every website encrypted.

**Comment by Arthur2e5** [comment]
Now it's 2016 and people can get certs from Let's Encrypt for free……

**Comment by hickford** [comment]
https://mate-desktop.com/ works partially but has mixed content issues

**Comment by Artoria2e5** [comment]
Looks like the CSS's needs to have their addresses written in some `//mate-desktop.com/` form.

**Comment by hickford** [comment]
The offending line of html is 

    <base href="http://mate-desktop.com/">

**Comment by flexiondotorg** [comment]
The site is available via http and https. The mixed content issue have been fixed.

**Comment by hickford** [comment]
Great work, thanks

**Comment by Artoria2e5** [comment]
Folks looking to write HTTPS Everywhere rules: pub, wiki, git, and planet also works over HTTPS.
