### ISSUE TITLE
xterm used to run console applications but not installed by default (15.04 64bit)

### ISSUE THREAD

**Issue by pasmanp** [mate-desktop/mate-desktop.org#44]
xterm is used to run console applications but is not installed by default.
when I try to run htop from menu , there is error: xterm not found.

**Comment by monsta** [comment]
@flexiondotorg: please close this one as offtopic.

**Comment by flexiondotorg** [comment]
Sadly this is not something MATE can solve, it is a distro issue. Please raise a bug at http://bugs.launchpad.net/ubuntu-mate
