### ISSUE TITLE
Problem with keyboard layout

### ISSUE THREAD

**Issue by maicardi** [mate-desktop/mate-desktop.org#50]
I've tried both Ubuntu-MATE 15.04 & 15.10; Fedora MATE 23: Debian MATE 8.2.

In ALL of these, I select italian IT keyboard while installing; after installation the keyboard layout is US while displaying IT layout in the tray area and in the Control Center.

To fix I have to add US layout, switch to "real" US, then switch back to IT.

**Comment by monsta** [comment]
This is a repository for mate-desktop.org website. Please file a report in libmatekbd repository instead.
