### ISSUE TITLE
Link to Indonesian translation is incorrectly labelled

### ISSUE THREAD

**Issue by abrowne** [mate-desktop/mate-desktop.org#51]
The link to the Indonesian translation is labeled "Inggris". I think this an error, like if the French link was "Anglais". Based on Wikipedia's label, it should be labelled "Bahasa Indonesia". (I'm not an Indonesian speaker, but my BA is in linguistics ;-)

**Comment by Fastbyte01** [comment]
Hi, you are right. The translation should be Bahasa Indonesia.

**Comment by monsta** [comment]
Looks like this name is picked from Nikola which is used on the website. Please contact Nikola developers about that (see Support & Contact menu at https://getnikola.com).

**Comment by abrowne** [comment]
I submitted [an issue](https://github.com/getnikola/nikola/issues/2291) with Nikola for this, thanks!

**Comment by Kwpolska** [comment]
We’re aware of this for quite some time, but nobody has stepped in to correct it. The Indonesian translation could use some more updates, too: https://www.transifex.com/ralsina/nikola/language/id/

Would an Indonesian speaker mind fixing those, preferably before Thursday? Thanks in advance.
