### ISSUE TITLE
Wrong Language

### ISSUE THREAD

**Issue by willysr** [mate-desktop/mate-desktop.org#54]
The text "Inggris" in (Also available in: ) should be "Bahasa Indonesia" and i posted a pull request on nikola and merged to master already (https://github.com/getnikola/nikola/commit/c1b80be814f2d959d51c37293587400e00966c15). 

perhaps the website should pull latest version from Nikola?

Thanks

**Comment by monsta** [comment]
@flexiondotorg: I agree, this should be fixed for Indonesian users.

**Comment by jrschmidt** [comment]
Just to make it clear, "Inggris" is Indonesian for "English".

"Bahasa Indonesia" is the name for the Indonesian language.

**Comment by willysr** [comment]
+1

**Comment by monsta** [comment]
Ok, "Bahasa Indonesia" is on the website now. Guess this can be closed?

**Comment by willysr** [comment]
It seems that it's only fixed in the index page, while other page still refer to old transations. Reopening this issue.

**Comment by monsta** [comment]
Hmm, but I also see "Bahasa Indonesia" link on Install, Development, Community, Team pages...

**Comment by willysr** [comment]
@monsta : See here
http://mate-desktop.com/id/community/
http://mate-desktop.com/id/development/
http://mate-desktop.com/id/install/
http://mate-desktop.com/id/team/

**Comment by willysr** [comment]
ups, yeah you are right. It should be reversed. Sorry
