### ISSUE TITLE
The wiki home page seems outdated

### ISSUE THREAD

**Issue by milouse** [mate-desktop/mate-desktop.org#71]
Under the development section (bottom of page) the stable version refers to the 2.8 and 2.8.x versions, while the unstable refers to the 2.10. They should respectively point to the 2.16 and 2.18 (or changelog page).

I try to open an account on the wiki to update the page but it seems newcomers cannot edit pages and find no information on how to contact an administrator to ask them to add me as an editor.

**Comment by raveit65** [comment]
Wiki is moved to github now https://github.com/mate-desktop/mate-wiki/
You can fix stuff with a pull request now.
