### ISSUE TITLE
Need fix blog-20170313-mate-1-18-released-md--master

### ISSUE THREAD

**Issue by usergreen** [mate-desktop/mate-desktop.org#718]
There are same type of issues in this blog. This is due to the editing style of the author. He sometimes splits a sentence between plural lines. It might be caused by WordPress as adopted in the past blog. As a result, this style cause a trouble in translating for another language.

As a turnaround, I managed to do by putting "\n" once in a while. For example:

line 68:  * NEWS: use consistent, project wide, markdown-like formatting
line 69:    to make generating release announcements easier

FYI
I hardly saw a case like this by other contributors.

**Comment by usergreen** [comment]
It was not a good idea. I replace "\n" with "&nbsp;" instead, as leaving it empty causes untranslated status on Transifex.

After all, it does not seem an  serious issue any more. Should I close now?

**Comment by raveit65** [comment]
yes, unnecessary work to change that all over the place
