### ISSUE TITLE
typo at blog-20180206-mate-1-20-released-md

### ISSUE THREAD

**Issue by usergreen** [mate-desktop/mate-desktop.org#720]
at line 189:
unncecessary --> unnecessary

**Comment by usergreen** [comment]
Line 340: libmate-panel-applet: unown bus name and unregister dbus object
unown bus name --> unknown bus name/or fix unknown bus name
I think the above is typo, so please confirm.

**Comment by usergreen** [comment]
Line 342: libmate-panel-applet: include dummy variable in factory for certian applets
certian applets --> certain applets

**Comment by usergreen** [comment]
Line 345: limatepanel-applet: add panel-applet-private.h
limatepanel-applet --> libmate-panel-applet

**Comment by usergreen** [comment]
Line 366: clock: fix hovering over timezone text, causes panel to scale beyond screen limit
timezone text, --> timezone text

**Comment by raveit65** [comment]
Can you do a pull request please?

**Comment by raveit65** [comment]
No need for a PR , i will do it for myself.

**Comment by raveit65** [comment]
Are this all typos in this file?

**Comment by raveit65** [comment]
Btw., do you really want to translate all the commit messages. I don't think this is ncecessary.

**Comment by usergreen** [comment]
I am sorry I couldn't reply your earlier comments, because here in Japan was late at night.
Thanks a lot.
