### ISSUE TITLE
No information about mate 1.28.0 (and .1 and .2)

### ISSUE THREAD

**Issue by cweiske** [mate-desktop/mate-desktop.org#736]
The latest news on https://mate-desktop.org/ is
>  2021-08-10 09:00   MATE 1.26 released 

There is no mention of 1.28 or any 1.28.x patchlevel releases.

**Comment by lukefromdc** [comment]
Can someone help finish 
https://github.com/mate-desktop/mate-desktop.org/pull/734
or should I merge it as-is? We are WAAY behind on this, note that I do not have any kind of automatic grammar checking software and keep spellcheckers off by default

**Comment by cweiske** [comment]
Thank you!
