### ISSUE TITLE
Request to update the date of release in mate 1.28

### ISSUE THREAD

**Issue by Navaneethan3** [mate-desktop/mate-desktop.org#738]
Currently the website shows that mate 1.28.2 to be released on 2024-02-27 09:00( https://mate-desktop.org/blog/2024-02-27-mate-1-28-released/ ). I request the date to be updated to match the correct release date. Thank you

**Comment by mbkma** [comment]
It is more or less the correct date. The last package was publish 2024-02-26. See https://pub.mate-desktop.org/releases/1.28/
