### ISSUE TITLE
MATE mailing list server doesn't respond

### ISSUE THREAD

**Issue by DavidGriffith** [mate-desktop/mate-desktop.org#76]
I'd like to subscribe to the MATE mailing list so I can figure out how to selectively use bleeding edge MATE components rather than the ones supplied in the Debian APT repos.  But that website: http://ml.mate-desktop.org/listinfo/ takes too long to respond and leaves me with a blank page.

**Comment by Jorilx** [comment]
Still a problem :/

**Comment by flexiondotorg** [comment]
Unfortunately the MATE team have no plans to create new mailing lists. When we had them they were not well monitored and rarely posted to.

Pretty much all communication happens via our GitHub issues and IRC channel `#mate-dev` on Freenode. We welcome anyone to our IRC channel to discuss development issues :-)

**Comment by Jorilx** [comment]
Maybe it's possible to remove the "Come and join the debate on the MATE mailing list" on mate-desktop.org, then? :)
(Seriously, thanks for letting us know!)

**Comment by DavidGriffith** [comment]
Yes, please.  And perhaps mention why there's no mailing list?

**Comment by monsta** [comment]
@flexiondotorg: I did some cleanup at https://github.com/mate-desktop/mate-desktop.org/pull/78.
