### ISSUE TITLE
potential CI+CD issues

### ISSUE THREAD

**Issue by ng-0** [mate-desktop/mate-desktop.org#80]
As noted in https://github.com/mate-desktop/mate-desktop.org/pull/79#issuecomment-329750643

Your CI+CD is acting autonomous, and this would be a problem if you wouldn't have a git to rollback:
live changes can occur just through open PR, they do not have to be merged, once the CI checks finish the content of the PR appears on the live website.

Is this a design problem of the CI / your way to use it or "just" some other issue?

It's not an issue of authority as long as you have git, but it seems not to be in git, which is a small problem.

**Comment by ng-0** [comment]
You seem to no longer have a mailinglist, so I have to try to contact you this way.

**Comment by ng-0** [comment]
So why is this an issue? All obvious issues left aside, your public noted workflow for this repository includes:

- commit your changes, submit a pull request and one of the website maintainers will review your submission and publish it if it is suitable.

**Comment by monsta** [comment]
@flexiondotorg: please have a look at this issue...

**Comment by yetist** [comment]
Now we switched to Travis CI and fixed the CI/CD issues.
