### ISSUE TITLE
Broken images.

### ISSUE THREAD

**Issue by darkshram** [mate-desktop/mate-desktop.org#84]
Many images, including the ones used in the captcha, are 404. Example below.
CC @raveit65 @flexiondotorg
![pantallazo-2017-12-11 14-13-49](https://user-images.githubusercontent.com/10327500/33852116-dcf2a65c-de7e-11e7-99f6-d1f1b76d26dc.png)
![pantallazo-2017-12-11 14-11-39](https://user-images.githubusercontent.com/10327500/33852117-dd0d61fe-de7e-11e7-88b9-a0153aa39f2f.png)

**Comment by raveit65** [comment]
Wiki is moved to github now https://github.com/mate-desktop/mate-wiki/
You can fix stuff with a pull request now.
