### ISSUE TITLE
https://wiki.mate-desktop.org/roadmap is outdated and no longer accurate.

### ISSUE THREAD

**Issue by Michael-AU** [mate-desktop/mate-desktop.org#85]
https://wiki.mate-desktop.org/roadmap is outdated and no new information about the direction MATE is going in has been put up since February 2017. Since then MATE 1.18 has been released even though the road map indicates it is still being developed. Would it be possible for the road map to be updated and a general check of the entire website be done so people who are interested in the future of MATE can find the information easily?
Cheers
Michael.

**Comment by monsta** [comment]
Roadmap is updated for 1.20 and 1.22
