### ISSUE TITLE
Mailing List section should be removed from Community page

### ISSUE THREAD

**Issue by azaeddui** [mate-desktop/mate-desktop.org#87]
it's noted in #76 that the mailing list server is no longer a thing, however, there's still a section and link to it on the Community page (http://mate-desktop.org/community/) -- please remove.

**Comment by monsta** [comment]
We know - it will be done once @flexiondotorg accepts https://github.com/mate-desktop/mate-desktop.org/pull/78

**Comment by monsta** [comment]
Ok, it's done now.
